development:
    adapter: postgresql
    database: postgres
    username: postgres
    password: secret
    host: localhost
    encoding: UTF8
production:
  adapter: postgresql
  database: caillou 
  pool: 5
  timeout: 5000

